version: "3.1"
  
services:

  db:
    image: postgres
    restart: always
    ports:
      - "35432:5432"
    environment:
      POSTGRES_PASSWORD: "dev"
      POSTGRES_USER: "dev"
      POSTGRES_DB: "dev"
